import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public final class SupabaseInitializer {

    private SupabaseInitializer() {
    }

    public static void initialize() {
        try (Connection connection = Database.getConnection(); Statement statement = connection.createStatement()) {
            statement.execute("create table if not exists products ("
                + "id bigint generated by default as identity primary key,"
                + "name text not null,"
                + "category text not null,"
                + "stock integer not null default 0,"
                + "unit_price numeric(12,2) not null default 0,"
                + "supplier_id integer not null default 1,"
                + "supplier_name text"
                + ")");

            statement.execute("create table if not exists suppliers ("
                + "id bigint generated by default as identity primary key,"
                + "name text not null,"
                + "category text,"
                + "email text,"
                + "phone text,"
                + "address text,"
                + "rating text"
                + ")");

            statement.execute("create table if not exists purchase_orders ("
                + "id bigint generated by default as identity primary key,"
                + "supplier_name text not null,"
                + "quantity integer not null,"
                + "unit_price numeric(12,2) not null,"
                + "status text not null,"
                + "order_date date not null default current_date"
                + ")");

            statement.execute("create table if not exists app_users ("
                + "username text primary key,"
                + "password text not null,"
                + "role text not null"
                + ")");

            statement.execute("create table if not exists app_preferences ("
                + "id integer primary key,"
                + "remember_me boolean not null default false,"
                + "remembered_username text"
                + ")");

            seedUsersIfEmpty(statement);
            seedPreferencesIfEmpty(statement);
        } catch (Exception exception) {
            throw new RuntimeException("Failed to initialize Supabase schema: " + exception.getMessage(), exception);
        }
    }

    private static void seedUsersIfEmpty(Statement statement) throws SQLException {
        try (ResultSet resultSet = statement.executeQuery("select count(*) from app_users")) {
            if (resultSet.next() && resultSet.getInt(1) == 0) {
                statement.executeUpdate("insert into app_users (username, password, role) values "
                    + "('admin', 'admin123', 'Administrator'),"
                    + "('manager', 'manager123', 'Inventory Manager'),"
                    + "('staff', 'staff123', 'Inventory Staff')");
            }
        }
    }

    private static void seedPreferencesIfEmpty(Statement statement) throws SQLException {
        try (ResultSet resultSet = statement.executeQuery("select count(*) from app_preferences")) {
            if (resultSet.next() && resultSet.getInt(1) == 0) {
                statement.executeUpdate("insert into app_preferences (id, remember_me, remembered_username) values (1, false, null)");
            }
        }
    }
}
